Use <a> for internal and external links links
tempus-finance/tempus-website pull request #62
Opened 2022-03-15 16:32 UTC by iamvukasin

* `color: transparent` is used to reset the default orange underline for links
* `ExternalLink` is the same as one from `tempus-app`

2022-03-15 16:45 UTC, danieledamiani commented on src/components/sections/main/main.tsx
> +        <Button width="206px" height="55px">
no inline styles please, use a class

2022-03-15 16:46 UTC, danieledamiani commented on src/components/token/sections/main/tokenMainSection.tsx
> +          <Button width="200px" height="48px">
remove the inline style please

2022-03-15 16:46 UTC, danieledamiani reviewed
lgtm

2022-03-15 18:27 UTC, ShawTim requested changes
as commented

2022-03-15 18:27 UTC, ShawTim commented on src/components/sections/footer/footer.scss
> +    color: #ffffff;
is it required?

2022-03-15 18:27 UTC, ShawTim commented on src/components/sections/main/main.scss
> +  color: transparent;
it's already `display: none` and we dont need to add `color: transparent` here.
it's not the scope of this task but we may consider to remove this element later

2022-03-15 18:27 UTC, ShawTim commented on src/components/sections/news/newsCard/newsCard.scss
> +  color: transparent;
i think `text-decoration: none;` maybe what you want to have instead of `color: transparent`

2022-03-15 18:27 UTC, ShawTim commented on src/components/sections/security/security.scss
> +  color: transparent;
same as above

2022-03-16 10:17 UTC, ShawTim approved these changes

2022-03-16 10:31 UTC, merged